### ISSUE TITLE
Issue with edge-to-edge display and inconsistent UI libraries usage

### ISSUE THREAD

**Issue by ngapp-dev** [piashcse/kmp-movie#11]
## Description:

There is an issue with the display of the top and bottom parts of the app on different devices due to the lack of edge-to-edge support. This results in misalignment and inconsistent padding, making the UI look incorrect on some screens.

Additionally, there is an inconsistency in the UI libraries used. Half of the app is built using Material components, while the other half uses Material 3 components. This inconsistency may lead to issues with visual coherence and behavior across different parts of the app.

## Steps to Reproduce:

	1.	Open the app on various devices with different screen sizes.
	2.	Observe the misalignment at the top and bottom of the screen.
	3.	Notice the different UI styles between Material and Material 3 components.

## Expected Behavior:

	•	The app should support edge-to-edge display for consistent alignment on all devices.
	•	The app should use a unified UI framework (either Material or Material 3) for consistency across the entire app.

## Actual Behavior:

	•	Top and bottom parts of the app are misaligned due to lack of edge-to-edge support.
	•	Inconsistent usage of Material and Material 3 components.

**Comment by piashcse** [comment]
Thank you so much @ngapp-dev for your valuable feedback and PR. Merged the PR and closing the issue 
Ref:
https://github.com/piashcse/kmp-movie/pull/10
